/**
 * 파 일 명 : TransForCST171.java
 * 설    명 : 
 * 작 성 자 : jhlee
 * 작 성 일 : 2009-06-24 오후 3:30:00
 * 변경내역 :
 * 
 */
package com.helco.xf.cs12.batch;

import java.sql.Connection;
import java.sql.SQLException;
import tit.service.core.logger.Logger;
import com.helco.xf.cs12.evladm.dbutil.LoggablePreparedStatement;

public class TransForCST171
{
	static Logger logger;

	/**
	* 작성자 : jhlee
	* 작성일 : 2009.06.24
	* 설  명 : 현재 월 보수 사업계획정보 집계 DELETE
	* 기  타 : 
	*/
	public int delProcForCST171(String mandt, Connection conn, String yym2) throws SQLException, Exception
	{
		logger.debug("==> [보수 사업계획정보 집계] 삭제 시작 ");
		StringBuffer               sqlBuff  = new StringBuffer();
		LoggablePreparedStatement  pstmt    = null;

		sqlBuff.append(" DELETE                \n");
		sqlBuff.append("   FROM                \n");
		sqlBuff.append("        SAPHEE.ZCST171 \n");
		sqlBuff.append("  WHERE                \n");
		sqlBuff.append("        MANDT = ?      \n");
		sqlBuff.append("    AND CS171_YYM = ?  \n");

		try
		{
			int idxparam = 1;
			pstmt = new LoggablePreparedStatement(conn, sqlBuff.toString());

			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym2);

			pstmt.executeUpdate();
		}
		catch(Exception e)
		{
			throw e;
		}
		finally
		{
			BatchConstants.close(null,pstmt,null);            
		}
		logger.debug("==> [보수 사업계획정보 집계] 삭제 종료 ");
		return 0;
	}

	/**
	* 작성자 : jhlee
	* 작성일 : 2009.06.24
	* 설  명 : 현재 월 보수 사업계획정보 집계 INSERT
	* 기  타 : 
	*/
	public int ProcTransForCST171(String mandt, Connection conn, String yym1, String yym2) throws SQLException, Exception
	{
		logger.debug("==> [보수 사업계획정보 집계] 저장 시작");
		StringBuffer               sqlBuff  = new StringBuffer();
		LoggablePreparedStatement  pstmt    = null;

		sqlBuff.append(" INSERT                                                                                                                                                                                                                                                    \n");
		sqlBuff.append("        INTO SAPHEE.ZCST171                                                                                                                                                                                                                                \n");
		sqlBuff.append("         SELECT                                                                                                                                                                                                                                            \n");
		sqlBuff.append("                CAST(? AS VARCHAR(3)),                                                                                                                                                                                                                     \n");
		sqlBuff.append("                CAST(? AS VARCHAR(6)),                                                                                                                                                                                                                     \n");
		sqlBuff.append("                X.ARA,                                                                                                                                                                                                                                     \n");
		sqlBuff.append("                X.GBU,                                                                                                                                                                                                                                     \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT01 WHEN '3' THEN X.CNT02 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT04 WHEN '3' THEN X.CNT05 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT07 WHEN '3' THEN X.CNT08 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT10 WHEN '3' THEN X.CNT11 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT13 WHEN '3' THEN X.CNT14 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT16 WHEN '3' THEN X.CNT17 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT19 WHEN '3' THEN X.CNT20 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT22 WHEN '3' THEN X.CNT23 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT41 WHEN '3' THEN X.CNT42 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                DECIMAL(ROUND(CASE X.GBU WHEN '1' THEN X.CNT25 WHEN '3' THEN X.CNT26 ELSE 0 END,2),6,2),                                                                                                                                                   \n");
		sqlBuff.append("                DECIMAL(ROUND(CASE X.GBU WHEN '1' THEN X.CNT27 ELSE 0 END,2),6,2),                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT28 WHEN '3' THEN X.CNT29 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT31 WHEN '3' THEN X.CNT32 ELSE 0 END,                                                                                                                                                                         \n");
		sqlBuff.append("                DECIMAL(ROUND(CASE X.GBU WHEN '1' THEN X.CNT34 WHEN '3' THEN X.CNT35 ELSE 0 END,3),6,2),                                                                                                                                                   \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT37 ELSE 0 END,                                                                                                                                                                                               \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT38 ELSE 0 END,                                                                                                                                                                                               \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT39 ELSE 0 END,                                                                                                                                                                                               \n");
		sqlBuff.append("                CASE X.GBU WHEN '1' THEN X.CNT40 ELSE 0 END,                                                                                                                                                                                               \n");
		sqlBuff.append("                '',                                                                                                                                                                                                                                        \n");
		sqlBuff.append("                HEX(CURRENT DATE),                                                                                                                                                                                                                         \n");
		sqlBuff.append("                HEX(CURRENT TIME),                                                                                                                                                                                                                         \n");
		sqlBuff.append("                'SYSTEM'                                                                                                                                                                                                                                   \n");
		sqlBuff.append("           FROM                                                                                                                                                                                                                                            \n");
		sqlBuff.append("                (                                                                                                                                                                                                                                          \n");
		sqlBuff.append("                 SELECT                                                                                                                                                                                                                                    \n");
		sqlBuff.append("                        I.GBU,                                                                                                                                                                                                                             \n");
		sqlBuff.append("                        A.ARA,                                                                                                                                                                                                                             \n");
		sqlBuff.append("                        A.ARA_NM,                                                                                                                                                                                                                          \n");
		sqlBuff.append("                        VALUE(F.CNT_A,0) CNT01,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(F.CNT_B,0) CNT02,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(F.CNT_C,0) CNT03,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(C.CNT_A,0) CNT04,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(C.CNT_B,0) CNT05,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(C.CNT_C,0) CNT06,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_D,0) CNT07,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_E,0) CNT08,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_F,0) CNT09,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(D.CNT_A,0) CNT10,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(D.CNT_B,0) CNT11,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(D.CNT_C,0) CNT12,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(F.CNT_D,0) CNT13,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(F.CNT_E,0) CNT14,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(F.CNT_F,0) CNT15,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(C.CNT_D,0) CNT16,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(C.CNT_E,0) CNT17,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(C.CNT_F,0) CNT18,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_J,0) CNT19,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_K,0) CNT20,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_L,0) CNT21,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(D.CNT_D,0) CNT22,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(D.CNT_E,0) CNT23,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(D.CNT_F,0) CNT24,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        (DOUBLE(VALUE(D.CNT_D,0)) / DOUBLE((VALUE(B.CNT_G,0) + VALUE(D.CNT_D,0))) * 100) CNT25,                                                                                                                                            \n");
		sqlBuff.append("                        CASE WHEN VALUE(B.CNT_H,0) = 0 OR VALUE(D.CNT_E,0) = 0 THEN 0 ELSE (DOUBLE(VALUE(D.CNT_E,0)) / DOUBLE((VALUE(B.CNT_H,0) + VALUE(D.CNT_E,0))) * 100) END CNT26,                                                                     \n");
		sqlBuff.append("                        (DOUBLE(VALUE(D.CNT_F,0)) / DOUBLE((VALUE(B.CNT_I,0) + VALUE(D.CNT_F,0))) * 100) CNT27,                                                                                                                                            \n");
		sqlBuff.append("                        (VALUE(F.CNT_D,0) + VALUE(C.CNT_D,0) + VALUE(B.CNT_J,0) - VALUE(D.CNT_D,0)) CNT28,                                                                                                                                                 \n");
		sqlBuff.append("                        (VALUE(F.CNT_E,0) + VALUE(C.CNT_E,0) + VALUE(B.CNT_K,0) - VALUE(D.CNT_E,0)) CNT29,                                                                                                                                                 \n");
		sqlBuff.append("                        (VALUE(F.CNT_F,0) + VALUE(C.CNT_F,0) + VALUE(B.CNT_L,0) - VALUE(D.CNT_F,0)) CNT30,                                                                                                                                                 \n");
		sqlBuff.append("                        (VALUE(E.CNT_A,0) + VALUE(E.CNT_D,0) + VALUE(E.CNT_G,0)) CNT31,                                                                                                                                                                    \n");
		sqlBuff.append("                        (VALUE(E.CNT_B,0) + VALUE(E.CNT_E,0) + VALUE(E.CNT_H,0)) CNT32,                                                                                                                                                                    \n");
		sqlBuff.append("                        (VALUE(E.CNT_C,0) + VALUE(E.CNT_F,0) + VALUE(E.CNT_I,0)) CNT33,                                                                                                                                                                    \n");
		sqlBuff.append("                        ((DOUBLE(VALUE(E.CNT_A,0) + VALUE(E.CNT_D,0) + VALUE(E.CNT_G,0)) / DOUBLE(VALUE(E.CNT_C,0) + VALUE(E.CNT_F,0) + VALUE(E.CNT_I,0))) * 100) CNT34,                                                                                   \n");
		sqlBuff.append("                        ((DOUBLE(VALUE(E.CNT_B,0) + VALUE(E.CNT_E,0) + VALUE(E.CNT_H,0)) / DOUBLE(VALUE(E.CNT_C,0) + VALUE(E.CNT_F,0) + VALUE(E.CNT_I,0))) * 100) CNT35,                                                                                   \n");
		sqlBuff.append("                        ((DOUBLE(VALUE(E.CNT_C,0) + VALUE(E.CNT_F,0) + VALUE(E.CNT_I,0)) / DOUBLE(VALUE(E.CNT_C,0) + VALUE(E.CNT_F,0) + VALUE(E.CNT_I,0))) * 100) CNT36,                                                                                   \n");
		sqlBuff.append("                        (G.CNT / H.CNT) CNT37,                                                                                                                                                                                                             \n");
		sqlBuff.append("                        ((VALUE(E.CNT_A,0) + VALUE(E.CNT_D,0) + VALUE(E.CNT_G,0)) / H.CNT) CNT38,                                                                                                                                                          \n");
		sqlBuff.append("                        G.CNT CNT39,                                                                                                                                                                                                                       \n");
		sqlBuff.append("                        (VALUE(E.CNT_A,0) + VALUE(E.CNT_D,0) + VALUE(E.CNT_G,0)) CNT40,                                                                                                                                                                    \n");
		sqlBuff.append("                        VALUE(B.CNT_G,0) CNT41,                                                                                                                                                                                                            \n");
		sqlBuff.append("                        VALUE(B.CNT_H,0) CNT42                                                                                                                                                                                                             \n");
		sqlBuff.append("                   FROM                                                                                                                                                                                                                                    \n");
		sqlBuff.append("                        (                                                                                                                                                                                                                                  \n");
		sqlBuff.append("                         SELECT                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                A.CODE2 ARA,                                                                                                                                                                                                               \n");
		sqlBuff.append("                                A.CTEXT2 ARA_NM                                                                                                                                                                                                            \n");
		sqlBuff.append("                           FROM                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                SAPHEE.ZLCODE A                                                                                                                                                                                                            \n");
		sqlBuff.append("                          WHERE                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                A.MANDT = ?                                                                                                                                                                                                                \n");
		sqlBuff.append("                            AND A.CODE1 = 'CS115'                                                                                                                                                                                                          \n");
		sqlBuff.append("                            AND A.CODE2 <> 'E1'                                                                                                                                                                                                            \n");
		sqlBuff.append("                            AND A.LANG = 'ko'                                                                                                                                                                                                              \n");
		sqlBuff.append("                        ) A LEFT OUTER JOIN                                                                                                                                                                                                                \n");
		sqlBuff.append("                                            (                                                                                                                                                                                                              \n");
		sqlBuff.append("                                             SELECT                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.CS126_ARA ARA,                                                                                                                                                                                       \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS126_USD,1,6) = ? AND A.CS126_TGB = '1' AND (A.CS126_GKD = '2' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) <> 'M')) THEN 1 ELSE 0 END) CNT_A,                            \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS126_USD,1,6) = ? AND A.CS126_TGB = '3' AND (A.CS126_GKD = '2' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) <> 'M')) THEN 1 ELSE 0 END) CNT_B,                            \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS126_USD,1,6) = ? AND (A.CS126_GKD = '2' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) <> 'M')) THEN 1 ELSE 0 END) CNT_C,                                                  \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS126_USD,1,6) = ? AND A.CS126_TGB = '1' AND (A.CS126_GKD = '4' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) = 'M')) THEN 1 ELSE 0 END) CNT_D,                             \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS126_USD,1,6) = ? AND A.CS126_TGB = '3' AND (A.CS126_GKD = '4' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) = 'M')) THEN 1 ELSE 0 END) CNT_E,                             \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS126_USD,1,6) = ? AND A.CS126_GKD = '4' OR (SUBSTR(A.CS126_USD,1,6) = ? AND A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) = 'M') THEN 1 ELSE 0 END) CNT_F,                     \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS126_TGB = '1' AND (A.CS126_GKD = '2' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) <> 'M')) THEN 1 ELSE 0 END) CNT_G,                                                            \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS126_TGB = '3' AND (A.CS126_GKD = '2' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) <> 'M')) THEN 1 ELSE 0 END) CNT_H,                                                            \n");
		sqlBuff.append("                                                    SUM(CASE WHEN (A.CS126_GKD = '2' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) <> 'M')) THEN 1 ELSE 0 END) CNT_I,                                                                                  \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS126_TGB = '1' AND (A.CS126_GKD = '4' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) = 'M')) THEN 1 ELSE 0 END) CNT_J,                                                             \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS126_TGB = '3' AND (A.CS126_GKD = '4' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) = 'M')) THEN 1 ELSE 0 END) CNT_K,                                                             \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS126_GKD = '4' OR (A.CS126_GKD = '5' AND SUBSTR(A.CS126_PJT,1,1) = 'M') THEN 1 ELSE 0 END) CNT_L                                                                                      \n");
		sqlBuff.append("                                               FROM                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SAPHEE.ZCST126 A,                                                                                                                                                                                      \n");
		sqlBuff.append("                                                    (                                                                                                                                                                                                      \n");
		sqlBuff.append("                                                     SELECT                                                                                                                                                                                                \n");
		sqlBuff.append("                                                            C.MANDT,                                                                                                                                                                                       \n");
		sqlBuff.append("                                                            C.CS126_UPN,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            C.CS126_CST,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            C.CS126_PJT,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            C.CS126_HNO,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            MAX(C.CS126_SEQ) CS126_SEQ                                                                                                                                                                     \n");
		sqlBuff.append("                                                       FROM                                                                                                                                                                                                \n");
		sqlBuff.append("                                                            SAPHEE.ZCST126 C                                                                                                                                                                               \n");
		sqlBuff.append("                                                      WHERE                                                                                                                                                                                                \n");
		sqlBuff.append("                                                            C.MANDT = ?                                                                                                                                                                                    \n");
		sqlBuff.append("                                                        AND C.CS126_DDT = ''                                                                                                                                                                               \n");
		sqlBuff.append("                                                        AND C.CS126_ARA > ''                                                                                                                                                                               \n");
		sqlBuff.append("                                                        AND C.CS126_BSU > ''                                                                                                                                                                               \n");
		sqlBuff.append("                                                        AND C.CS126_DDT = ''                                                                                                                                                                               \n");
		sqlBuff.append("                                                        AND C.CS126_PST = 'A6'                                                                                                                                                                             \n");
		sqlBuff.append("                                                        AND SUBSTR(C.CS126_HNO,1,1) NOT IN ('J','G')                                                                                                                                                       \n");
		sqlBuff.append("                                                        AND C.CS126_USD BETWEEN ? || '01' AND ? || '31'                                                                                                                                                    \n");
		sqlBuff.append("                                                     GROUP BY                                                                                                                                                                                              \n");
		sqlBuff.append("                                                            C.MANDT,                                                                                                                                                                                       \n");
		sqlBuff.append("                                                            C.CS126_UPN,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            C.CS126_CST,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            C.CS126_PJT,                                                                                                                                                                                   \n");
		sqlBuff.append("                                                            C.CS126_HNO                                                                                                                                                                                    \n");
		sqlBuff.append("                                                    ) B,                                                                                                                                                                                                   \n");
		sqlBuff.append("                                                    SAPHEE.ZCST111 C                                                                                                                                                                                       \n");
		sqlBuff.append("                                              WHERE                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.MANDT = ?                                                                                                                                                                                            \n");
		sqlBuff.append("                                                AND A.MANDT = B.MANDT                                                                                                                                                                                      \n");
		sqlBuff.append("                                                AND A.CS126_UPN = B.CS126_UPN                                                                                                                                                                              \n");
		sqlBuff.append("                                                AND A.CS126_CST = B.CS126_CST                                                                                                                                                                              \n");
		sqlBuff.append("                                                AND A.CS126_PJT = B.CS126_PJT                                                                                                                                                                              \n");
		sqlBuff.append("                                                AND A.CS126_HNO = B.CS126_HNO                                                                                                                                                                              \n");
		sqlBuff.append("                                                AND A.CS126_SEQ = B.CS126_SEQ                                                                                                                                                                              \n");
		sqlBuff.append("                                                AND A.MANDT = C.MANDT                                                                                                                                                                                      \n");
		sqlBuff.append("                                                AND A.CS126_PJT = C.PJT                                                                                                                                                                                    \n");
		sqlBuff.append("                                                AND A.CS126_HNO = C.HNO                                                                                                                                                                                    \n");
		sqlBuff.append("                                                AND C.HST NOT IN ('D','F')                                                                                                                                                                                 \n");
		sqlBuff.append("                                                AND A.CS126_ARA > ''                                                                                                                                                                                       \n");
		sqlBuff.append("                                                AND A.CS126_BSU > ''                                                                                                                                                                                       \n");
		sqlBuff.append("                                                AND A.CS126_DDT = ''                                                                                                                                                                                       \n");
		sqlBuff.append("                                                AND A.CS126_PST = 'A6'                                                                                                                                                                                     \n");
		sqlBuff.append("                                                AND SUBSTR(A.CS126_HNO,1,1) NOT IN ('J','G')                                                                                                                                                               \n");
		sqlBuff.append("                                                AND A.CS126_USD BETWEEN ? || '01' AND ? || '31'                                                                                                                                                            \n");
		sqlBuff.append("                                             GROUP BY                                                                                                                                                                                                      \n");
		sqlBuff.append("                                                    A.CS126_ARA                                                                                                                                                                                            \n");
		sqlBuff.append("                                            ) B ON A.ARA = B.ARA                                                                                                                                                                                           \n");
		sqlBuff.append("                            LEFT OUTER JOIN                                                                                                                                                                                                                \n");
		sqlBuff.append("                                            (                                                                                                                                                                                                              \n");
		sqlBuff.append("                                             SELECT                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.ARA,                                                                                                                                                                                                 \n");
		sqlBuff.append("                                                    SUM(CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_IGM,'') = ? AND VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1' THEN 1                                                                                         \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_IGM,'') = ? AND VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3' THEN -1                                                                                        \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END) CNT_A,                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SUM(CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_IGM,'') = ? AND VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3' THEN 1                                                                                         \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_IGM,'') = ? AND VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1' THEN -1                                                                                        \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END) CNT_B,                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SUM(CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_IGM,'') = ? AND ((VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1') OR (VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3')) THEN 1                    \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_IGM,'') = ? AND ((VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3') OR (VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1')) THEN -1                   \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END) CNT_C,                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SUM(CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1' THEN 1                                                                                                                       \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3' THEN -1                                                                                                                      \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END) CNT_D,                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SUM(CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3' THEN 1                                                                                                                       \n");
		sqlBuff.append("                                                             WHEN VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1' THEN -1                                                                                                                      \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END) CNT_E,                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SUM(CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN (VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1') OR (VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3') THEN 1                                                    \n");
		sqlBuff.append("                                                             WHEN (VALUE(B.CS157_GHB,'') = '1' AND VALUE(B.CS157_GHA,'') = '3') OR (VALUE(B.CS157_GHB,'') = '3' AND VALUE(B.CS157_GHA,'') = '1') THEN -1                                                   \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END) CNT_F                                                                                                                                                                                         \n");
		sqlBuff.append("                                               FROM                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SAPHEE.ZCST111 A                                                                                                                                                                                       \n");
		sqlBuff.append("                                                           LEFT OUTER JOIN SAPHEE.ZCST157 B ON A.MANDT = B.MANDT                                                                                                                                           \n");
		sqlBuff.append("                                                                                           AND A.PJT = B.CS157_PJT                                                                                                                                         \n");
		sqlBuff.append("                                                                                           AND A.HNO = B.CS157_HNO                                                                                                                                         \n");
		sqlBuff.append("                                                                                           AND B.CS157_RLT = 'Y'                                                                                                                                           \n");
		sqlBuff.append("                                              WHERE                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.MANDT = ?                                                                                                                                                                                            \n");
		sqlBuff.append("                                                AND A.ARA > ''                                                                                                                                                                                             \n");
		sqlBuff.append("                                                AND A.BSU > ''                                                                                                                                                                                             \n");
		sqlBuff.append("                                                AND A.HST <> 'D'                                                                                                                                                                                           \n");
		sqlBuff.append("                                                AND SUBSTR(A.HNO,1,1) NOT IN ('J','G')                                                                                                                                                                     \n");
		sqlBuff.append("                                                AND VALUE(B.CS157_IGM,'') BETWEEN ? AND ?                                                                                                                                                                  \n");
		sqlBuff.append("                                             GROUP BY                                                                                                                                                                                                      \n");
		sqlBuff.append("                                                    A.ARA                                                                                                                                                                                                  \n");
		sqlBuff.append("                                            ) C ON A.ARA = C.ARA                                                                                                                                                                                           \n");
		sqlBuff.append("                            LEFT OUTER JOIN                                                                                                                                                                                                                \n");
		sqlBuff.append("                                            (                                                                                                                                                                                                              \n");
		sqlBuff.append("                                             SELECT                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.ARA,                                                                                                                                                                                                 \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.FSD,1,6) = ? AND A.GBU = '1' THEN 1 ELSE 0 END) CNT_A,                                                                                                                          \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.FSD,1,6) = ? AND A.GBU = '3' THEN 1 ELSE 0 END) CNT_B,                                                                                                                          \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.FSD,1,6) = ? THEN 1 ELSE 0 END) CNT_C,                                                                                                                                          \n");
		sqlBuff.append("                                                    SUM(CASE A.GBU WHEN '1' THEN 1 ELSE 0 END) CNT_D,                                                                                                                                                      \n");
		sqlBuff.append("                                                    SUM(CASE A.GBU WHEN '3' THEN 1 ELSE 0 END) CNT_E,                                                                                                                                                      \n");
		sqlBuff.append("                                                    COUNT(*) CNT_F                                                                                                                                                                                         \n");
		sqlBuff.append("                                               FROM                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SAPHEE.ZCST111 A                                                                                                                                                                                       \n");
		sqlBuff.append("                                              WHERE                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.MANDT = ?                                                                                                                                                                                            \n");
		sqlBuff.append("                                                AND A.ARA > ''                                                                                                                                                                                             \n");
		sqlBuff.append("                                                AND A.BSU > ''                                                                                                                                                                                             \n");
		sqlBuff.append("                                                AND A.HST = 'F'                                                                                                                                                                                            \n");
		sqlBuff.append("                                                AND A.FSD > ''                                                                                                                                                                                             \n");
		sqlBuff.append("                                                AND SUBSTR(A.HNO,1,1) NOT IN ('J','G')                                                                                                                                                                     \n");
		sqlBuff.append("                                                AND A.FSD BETWEEN ? || '01' AND ? || '31'                                                                                                                                                                  \n");
		sqlBuff.append("                                             GROUP BY                                                                                                                                                                                                      \n");
		sqlBuff.append("                                                    A.ARA                                                                                                                                                                                                  \n");
		sqlBuff.append("                                            ) D ON A.ARA = D.ARA                                                                                                                                                                                           \n");
		sqlBuff.append("                            LEFT OUTER JOIN                                                                                                                                                                                                                \n");
		sqlBuff.append("                                            (                                                                                                                                                                                                              \n");
		sqlBuff.append("                                             SELECT                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.ARA,                                                                                                                                                                                                 \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.BSU > '' AND A.GBU = '1' AND A.HST IN ('S','M') THEN 1 ELSE 0 END) CNT_A,                                                                                                              \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.BSU > '' AND A.GBU = '3' AND A.HST IN ('S','M') THEN 1 ELSE 0 END) CNT_B,                                                                                                              \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.BSU > '' AND A.HST IN ('S','M') THEN 1 ELSE 0 END) CNT_C,                                                                                                                              \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.BSU > '' AND A.GBU = '1' AND A.HST IN ('B','H','U') THEN 1 ELSE 0 END) CNT_D,                                                                                                          \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.BSU > '' AND A.GBU = '3' AND A.HST IN ('B','H','U') THEN 1 ELSE 0 END) CNT_E,                                                                                                          \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.BSU > '' AND A.HST IN ('B','H','U') THEN 1 ELSE 0 END) CNT_F,                                                                                                                          \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.GBU = '1' AND A.BSU > '' AND A.HST = '' THEN 1 ELSE 0 END) CNT_G,                                                                                                                      \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.HST IN ('','K') AND (A.GBU = '3' OR A.BSU = '') THEN 1 ELSE 0 END) CNT_H,                                                                                                              \n");
		sqlBuff.append("                                                    SUM(                                                                                                                                                                                                   \n");
		sqlBuff.append("                                                        CASE                                                                                                                                                                                               \n");
		sqlBuff.append("                                                             WHEN A.GBU = '1' AND A.BSU > '' AND A.HST = '' THEN 1                                                                                                                                         \n");
		sqlBuff.append("                                                             WHEN A.HST IN ('','K') AND (A.GBU = '3' OR A.BSU = '') THEN 1                                                                                                                                 \n");
		sqlBuff.append("                                                             ELSE 0                                                                                                                                                                                        \n");
		sqlBuff.append("                                                        END                                                                                                                                                                                                \n");
		sqlBuff.append("                                                    ) CNT_I                                                                                                                                                                                                \n");
		sqlBuff.append("                                               FROM                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SAPHEE.ZCST111 A                                                                                                                                                                                       \n");
		sqlBuff.append("                                              WHERE                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.MANDT = ?                                                                                                                                                                                            \n");
		sqlBuff.append("                                                AND A.ARA > ''                                                                                                                                                                                             \n");
		sqlBuff.append("                                                AND SUBSTR(A.HNO,1,1) NOT IN ('J','G')                                                                                                                                                                     \n");
		sqlBuff.append("                                                AND A.HST IN ('','K','B','S','H','M','U')                                                                                                                                                                  \n");
		sqlBuff.append("                                             GROUP BY                                                                                                                                                                                                      \n");
		sqlBuff.append("                                                    A.ARA                                                                                                                                                                                                  \n");
		sqlBuff.append("                                            ) E ON A.ARA = E.ARA                                                                                                                                                                                           \n");
		sqlBuff.append("                            LEFT OUTER JOIN                                                                                                                                                                                                                \n");
		sqlBuff.append("                                            (                                                                                                                                                                                                              \n");
		sqlBuff.append("                                             SELECT                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.CS101_ARA ARA,                                                                                                                                                                                       \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS101_IGD,1,6) = ? AND A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '1' THEN 1 ELSE 0 END) CNT_A,                                                                                   \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS101_IGD,1,6) = ? AND (A.CS101_PST = 'A1' OR (A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '3')) THEN 1 ELSE 0 END) CNT_B,                                                         \n");
		sqlBuff.append("                                                    SUM(CASE WHEN SUBSTR(A.CS101_IGD,1,6) = ? AND ((A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '1') OR (A.CS101_PST = 'A1' OR (A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '3'))) THEN 1 ELSE 0 END) CNT_C,     \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '1' THEN 1 ELSE 0 END) CNT_D,                                                                                                                   \n");
		sqlBuff.append("                                                    SUM(CASE WHEN A.CS101_PST = 'A1' OR (A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '3') THEN 1 ELSE 0 END) CNT_E,                                                                                           \n");
		sqlBuff.append("                                                    SUM(CASE WHEN ((A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '1') OR (A.CS101_PST = 'A1' OR (A.CS101_PST = 'A6' AND VALUE(B.GBU,'') = '3'))) THEN 1 ELSE 0 END) CNT_F                                      \n");
		sqlBuff.append("                                               FROM                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    SAPHEE.ZCST101 A                                                                                                                                                                                       \n");
		sqlBuff.append("                                                           LEFT OUTER JOIN SAPHEE.ZCST111 B ON A.MANDT = B.MANDT                                                                                                                                           \n");
		sqlBuff.append("                                                                                           AND A.CS101_PJT = B.PJT                                                                                                                                         \n");
		sqlBuff.append("                                                                                           AND A.CS101_HNO = B.HNO                                                                                                                                         \n");
		sqlBuff.append("                                              WHERE                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    A.MANDT = ?                                                                                                                                                                                            \n");
		sqlBuff.append("                                                AND SUBSTR(A.CS101_HNO,1,1) NOT IN ('J','G')                                                                                                                                                               \n");
		sqlBuff.append("                                                AND A.CS101_IGD BETWEEN ? || '01' AND ? || '31'                                                                                                                                                            \n");
		sqlBuff.append("                                             GROUP BY                                                                                                                                                                                                      \n");
		sqlBuff.append("                                                    A.CS101_ARA                                                                                                                                                                                            \n");
		sqlBuff.append("                                            ) F ON A.ARA = F.ARA,                                                                                                                                                                                          \n");
		sqlBuff.append("                        (                                                                                                                                                                                                                                  \n");
		sqlBuff.append("                         SELECT                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                A.ARA,                                                                                                                                                                                                                     \n");
		sqlBuff.append("                                SUM(                                                                                                                                                                                                                       \n");
		sqlBuff.append("                                    CASE WHEN A.GBU = '1' AND A.BSU > '' AND A.HST IN ('','S','B','H','M','U') THEN                                                                                                                                        \n");
		sqlBuff.append("                                    (                                                                                                                                                                                                                      \n");
		sqlBuff.append("                                     CASE                                                                                                                                                                                                                  \n");
		sqlBuff.append("                                          WHEN B.ZZGUBUN IN ('10','13') THEN                                                                                                                                                                               \n");
		sqlBuff.append("                                               CASE                                                                                                                                                                                                        \n");
		sqlBuff.append("                                                    WHEN INT(CASE B.ZSPEC7 WHEN '' THEN '0' ELSE B.ZSPEC7 END) < 10 THEN 0.8                                                                                                                               \n");
		sqlBuff.append("                                                    ELSE 1 - ((15 - INT(CASE B.ZSPEC7 WHEN '' THEN '0' ELSE B.ZSPEC7 END)) * 0.04)                                                                                                                         \n");
		sqlBuff.append("                                               END                                                                                                                                                                                                         \n");
		sqlBuff.append("                                          WHEN B.ZZGUBUN IN ('11','12','14') THEN 1.8                                                                                                                                                                      \n");
		sqlBuff.append("                                          ELSE 0                                                                                                                                                                                                           \n");
		sqlBuff.append("                                     END                                                                                                                                                                                                                   \n");
		sqlBuff.append("                                    )                                                                                                                                                                                                                      \n");
		sqlBuff.append("                                    ELSE 0 END                                                                                                                                                                                                             \n");
		sqlBuff.append("                                ) CNT                                                                                                                                                                                                                      \n");
		sqlBuff.append("                           FROM                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                SAPHEE.ZCST111 A                                                                                                                                                                                                           \n");
		sqlBuff.append("                                       LEFT OUTER JOIN SAPHEE.ZMASTER02 B ON B.MANDT = A.MANDT                                                                                                                                                             \n");
		sqlBuff.append("                                                                         AND B.POSID = A.PJT                                                                                                                                                               \n");
		sqlBuff.append("                                                                         AND SUBSTR(B.POSID_1,7,3) = A.HNO                                                                                                                                                 \n");
		sqlBuff.append("                          WHERE                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                A.MANDT = ?                                                                                                                                                                                                                \n");
		sqlBuff.append("                            AND SUBSTR(A.HNO,1,1) NOT IN ('J','G')                                                                                                                                                                                         \n");
		sqlBuff.append("                            AND A.HST IN ('','B','H','K','S','M','U')                                                                                                                                                                                      \n");
		sqlBuff.append("                         GROUP BY                                                                                                                                                                                                                          \n");
		sqlBuff.append("                                A.MANDT,                                                                                                                                                                                                                   \n");
		sqlBuff.append("                                A.ARA                                                                                                                                                                                                                      \n");
		sqlBuff.append("                        ) G,                                                                                                                                                                                                                               \n");
		sqlBuff.append("                        (                                                                                                                                                                                                                                  \n");
		sqlBuff.append("                         SELECT                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                DPT1 ARA,                                                                                                                                                                                                                  \n");
		sqlBuff.append("                                SUM(CASE                                                                                                                                                                                                                   \n");
		sqlBuff.append("                                         WHEN DEPT LIKE 'E5%' THEN 1                                                                                                                                                                                       \n");
		sqlBuff.append("                                         WHEN SUBSTR(DEPT,3,2) = '05' AND SUBSTR(DEPT,7,2) IN ('01','02','04','08') THEN 1                                                                                                                                 \n");
		sqlBuff.append("                                         ELSE 0                                                                                                                                                                                                            \n");
		sqlBuff.append("                                    END                                                                                                                                                                                                                    \n");
		sqlBuff.append("                                ) AS CNT                                                                                                                                                                                                                   \n");
		sqlBuff.append("                           FROM                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                SAPHEE.ZHRT001                                                                                                                                                                                                             \n");
		sqlBuff.append("                          WHERE                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                SUBSTR(DEPT,1,2) BETWEEN 'G1' AND 'H2'                                                                                                                                                                                     \n");
		sqlBuff.append("                                OR DEPT IN ('E5030101','E5030102','E5030103','E5030201','E5030202','E5030203','E5030204','E5030207')                                                                                                                       \n");
		sqlBuff.append("                            AND LEAV = '00000000'                                                                                                                                                                                                          \n");
		sqlBuff.append("                            AND RANK <> ''                                                                                                                                                                                                                 \n");
		sqlBuff.append("                         GROUP BY DPT1_N,DPT1                                                                                                                                                                                                              \n");
		sqlBuff.append("                        ) H,                                                                                                                                                                                                                               \n");
		sqlBuff.append("                        (                                                                                                                                                                                                                                  \n");
		sqlBuff.append("                         SELECT                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                CHAR(COLCOUNT) GBU                                                                                                                                                                                                         \n");
		sqlBuff.append("                           FROM                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                SYSIBM.SYSTABLES                                                                                                                                                                                                           \n");
		sqlBuff.append("                          WHERE                                                                                                                                                                                                                            \n");
		sqlBuff.append("                                COLCOUNT IN (1,3)                                                                                                                                                                                                          \n");
		sqlBuff.append("                         GROUP BY                                                                                                                                                                                                                          \n");
		sqlBuff.append("                                COLCOUNT                                                                                                                                                                                                                   \n");
		sqlBuff.append("                        ) I                                                                                                                                                                                                                                \n");
		sqlBuff.append("                  WHERE                                                                                                                                                                                                                                    \n");
		sqlBuff.append("                        A.ARA = G.ARA                                                                                                                                                                                                                      \n");
		sqlBuff.append("                    AND A.ARA = H.ARA                                                                                                                                                                                                                      \n");
		sqlBuff.append("                ) X                                                                                                                                                                                                                                        \n");

		try
		{
			int idxparam = 1;
			pstmt = new LoggablePreparedStatement(conn, sqlBuff.toString());

			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym1);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym1);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym1);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym1);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);
			pstmt.setString(idxparam++, yym1);
			pstmt.setString(idxparam++, yym2);
			pstmt.setString(idxparam++, mandt);

			pstmt.executeUpdate();
		}
		catch(Exception e)
		{
			throw e;
		}
		finally
		{
			BatchConstants.close(null,pstmt,null);            
		}
		logger.debug("==> [보수 사업계획정보 집계] 저장 종료 ");
		return 0;
	}

	public TransForCST171(Logger pLogger)
	{
		logger = pLogger;
	}
}